id: P005635
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20198
  title: སྟོད་མངའ་རིས་ཀྱི་དགོན་སྡེའི་ལོ་རྒྱུས་དག་གསལ་མཐོང་བའི་མེ་ལོང
  author: ''
  volumes:
    e04d01ff234e4bb5ae89357038043b0c:
      image_group_id: I1PD28139
      title: ''
      volume_number: 1
      total_pages: 210
      base_file: v001.txt
