id: I334299A7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T02:21:37+00:00'
last_modified: '2022-06-08T05:27:22.386897+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20198
  title: སྟོད་མངའ་རིས་ཀྱི་དགོན་སྡེའི་ལོ་རྒྱུས་དག་གསལ་མཐོང་བའི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    823C:
      image_group_id: I1PD28139
      title: ''
      total_pages: 210
      order: 1
      base_file: 823C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
